on:
  push:
    branches:
    - main
    - staging
    - release/*

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

# Reference: https://docs.github.com/en/actions

      - name: FTP Deploy To CloudAccess Host.net
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: baizonnlearningcenter.cloudaccess.host
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./wp-content/themes/baizonntheme/ # Folder to upload from (in this case our theme)
          server-dir: ./public_html/wp-content/themes/baizonntheme/ # Folder to upload to
          secure: false # Cloud access does not support SFTP/SSH until plan upgrade!


# Reference: https://github.com/SamKirkland/FTP-Deploy-Action (SamKirkland, FTP-Deploy-Action)

