name: CSS Code Linting

on:
  pull_request:
    branches:
      - main
      - css-lint-test
  push:
    branches:
      - main
      - css-lint-test

jobs:
  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: npm install
        run: npm install
      - name: Lint CSS
        run: npm run lint:scss
