name: Deploy to Production

on:
  workflow_run:
    workflows: [".github/workflows/deployment.yml"]
    types:
      - completed

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Issue for Approval
        id: create_issue
        uses: actions/github-script@v6
        with:
          script: |
            const issue_title = 'Approval Needed: Deploy to Production';
            const issue_body = `
              The staging deployment has been completed successfully. 
              Please approve this deployment to proceed to production.
            
              To approve, add a comment with the word 'approved'.
            `;
            const new_issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue_title,
              body: issue_body
            });
            console.log('Issue created:', new_issue.data.url);
            core.setOutput('issue_number', new_issue.data.number);

      - name: Wait for Approval
        id: wait_for_approval
        run: |
          issue_number=${{ steps.create_issue.outputs.issue_number }}
          echo "Waiting for approval on issue #$issue_number"
          sleep 60

      - name: Check for Approval (Comment on Issue)
        id: check_approval
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = ${{ steps.create_issue.outputs.issue_number }};
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });

            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });

            const approval_comment = comments.data.some(comment => comment.body.includes('approved'));

            if (approval_comment) {
              console.log('Approval received, proceeding with production deployment.');
            } else {
              console.log('Approval not received yet.');
              core.setFailed('Approval not received yet.');
            }

      - name: Deploy to Production (FTP)
        if: ${{ steps.check_approval.outcome == 'success' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: thebaizonnlearningcenter.cloudaccess.host
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Folder to upload from
          server-dir: ./httpdocs/wp-content/themes/baizonntheme/ # Folder to upload to
          security: loose # Cloud access does not support SFTP/SSH until plan upgrade!


      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: List contents of httpdocs
        run: |
          ls -l ./httpdocs

      - name: Install WP Migrate DB Plugin on Staging
        run: |
          cd ./httpdocs
          wp plugin install wp-migrate-db --activate --path=./httpdocs

      - name: Export Database from Staging
        run: |
          cd ./httpdocs
          wp migrate-db --export=./httpdocs/wp-content/uploads/backup/staging-dump.sql --path=./httpdocs

      - name: Download Database from Staging
        run: |
          curl -O ftp://baizonnlearningcenter.cloudaccess.host/wp-content/uploads/backup/staging-dump.sql --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}

      - name: Upload Database to Production
        run: |
          curl -T staging-dump.sql ftp://thebaizonnlearningcenter.cloudaccess.host/wp-content/uploads/backup/staging-dump.sql --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}

      - name: Import Database to Production
        run: |
          cd ./httpdocs
          wp db import ./httpdocs/wp-content/uploads/backup/staging-dump.sql --path=./httpdocs



